import Footer from "@/components/ui/footer/Footer";
import Header from "@/components/ui/header/Header";
import type { Metadata } from "next";
import { Alumni_Sans_Collegiate_One, Gothic_A1, Rubik, Rubik_Bubbles, Rubik_Mono_One, Silkscreen } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const rubic = Rubik({
    weight: ["300", "400", "500", "600", "700", "800", "900"],
    style: ["normal", "italic"],
    subsets: ["latin"],
    display: "swap",
});
export const rubicBubbles = Rubik_Bubbles({
    weight: ["400"],
    subsets: ["latin"],
    display: "swap",
});
export const gothicA1 = Gothic_A1({
    weight: ["100", "200", "300", "400", "500", "600"],
    style: ["normal"],
    subsets: ["latin"],
    display: "swap",
});
export const alumni = Alumni_Sans_Collegiate_One({
    weight: ["400"],
    style: ["normal"],
    subsets: ["latin"],
    display: "swap",
});
export const rubicmono = Rubik_Mono_One({
    weight: ["400"],
    style: ["normal"],
    subsets: ["latin"],
    display: "swap",
});
export const silkscreen = Silkscreen({
    weight: ["400"],
    style: ["normal"],
    subsets: ["latin"],
    display: "swap",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const headersList = headers();
    const header_url = headersList.get("x-url") || undefined;
    let lastSegment = undefined;

    // URL 객체 생성
    if (header_url) {
        const url = new URL(header_url);

        // pathname에서 마지막 부분 추출
        const pathSegments = url.pathname.split("/");
        lastSegment = pathSegments.pop() || pathSegments.pop();
    }

    return (
        <html lang="ko" className={rubic.className}>
            <body className="w-full h-dvh p-[0px] m-[0px] box-border overflow-hidden">
                <div className="w-full h-full flex flex-col relative">
                    <Header slug={lastSegment} />
                    <main className="flex-1 h-full">{children}</main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
